# Generated by Django 5.1.6 on 2026-02-18 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formentry',
            options={'ordering': ['-created_at'], 'verbose_name': 'Entrée de formulaire', 'verbose_name_plural': 'Entrées de formulaire'},
        ),
        migrations.AlterField(
            model_name='formentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='formentry',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='formentry',
            name='message',
            field=models.TextField(verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='formentry',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='formentry',
            name='password_hash',
            field=models.CharField(max_length=64, verbose_name='Hash du mot de passe (SHA-256)'),
        ),
        migrations.AddIndex(
            model_name='formentry',
            index=models.Index(fields=['-created_at'], name='api_forment_created_edb319_idx'),
        ),
        migrations.AddIndex(
            model_name='formentry',
            index=models.Index(fields=['email'], name='api_forment_email_a302f7_idx'),
        ),
    ]
